"""Ce fichier définit quelques données, sous la forme de variables,
utiles au programme pendu"""

# Nom du fichier stockant les scores
nom_fichier_scores = "scores"

somme_initiale = 1000

# Liste des mots du pendu
liste_cartes = [
	"Pas de carte attribuée",
    "As de carreau",
    "Deux de carreau",
    "Trois de carreau",
    "Quatre de carreau",
    "Cinq de carreau",
    "Six de carreau",
    "Sept de carreau",
    "Huit de carreau",
    "Neuf de carreau",
    "Dix de carreau",
    "Valet de carreau",
    "Dame de carreau",
    "Roi de carreau",
    "As de coeur",
    "Deux de coeur",
    "Trois de coeur",
    "Quatre de coeur",
    "Cinq de coeur",
    "Six de coeur",
    "Sept de coeur",
    "Huit de coeur",
    "Neuf de coeur",
    "Dix de coeur",
    "Valet de coeur",
    "Dame de coeur",
    "Roi de coeur",
    "As de pique",
    "Deux de pique",
    "Trois de pique",
    "Quatre de pique",
    "Cinq de pique",
    "Six de pique",
    "Sept de pique",
    "Huit de pique",
    "Neuf de pique",
    "Dix de pique",
    "Valet de pique",
    "Dame de pique",
    "Roi de pique",
    "As de trefle",
    "Deux de trefle",
    "Trois de trefle",
    "Quatre de trefle",
    "Cinq de trefle",
    "Six de trefle",
    "Sept de trefle",
    "Huit de trefle",
    "Neuf de trefle",
    "Dix de trefle",
    "Valet de trefle",
    "Dame de trefle",
    "Roi de trefle",
]